// <auto-generated />
using System;
using MeeshoWebClone.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeeshoWebClone.Migrations
{
    [DbContext(typeof(MeeshoAppDbContext))]
    partial class MeeshoAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeeshoWebClone.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MeeshoWebClone.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("FreeDelivery")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SellerLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MeeshoWebClone.Models.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e11df8a2-0774-4ee7-85e2-59e182f5e4f0"),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("4b619324-97e5-4d6b-a5e3-ea0ac516b9eb"),
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = new Guid("7f593cf7-15f1-46c0-b93b-7af512156c18"),
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = new Guid("725ee4d6-1394-4903-be0e-a234f8aa999d"),
                            Name = "Beauty & Personal Care"
                        },
                        new
                        {
                            Id = new Guid("2c90d1ad-5e84-41b0-972a-a2d2ac9b1ad1"),
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = new Guid("471744b9-9c60-42b2-92f1-fbc167cfd5a1"),
                            Name = "Books"
                        },
                        new
                        {
                            Id = new Guid("adbceca7-99e9-4d31-ae07-d85bfa5741a1"),
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = new Guid("29514917-e92e-4b79-86ec-f963f0a5359c"),
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = new Guid("fa3f4e46-efc2-4d33-9a9c-3d79ca6eeb4d"),
                            Name = "Jewelry & Accessories"
                        },
                        new
                        {
                            Id = new Guid("d0039229-13e2-47dd-86d4-cb32860209b0"),
                            Name = "Health & Wellness"
                        },
                        new
                        {
                            Id = new Guid("41f7f098-b5e8-43a2-86c5-6a6394f25ca0"),
                            Name = "Mobile Phones & Accessories"
                        },
                        new
                        {
                            Id = new Guid("77a92645-36da-4a79-bdce-f3925cd808b9"),
                            Name = "Office Supplies"
                        },
                        new
                        {
                            Id = new Guid("9ffb6c69-3072-4d6b-b3ac-4dca2bc422ed"),
                            Name = "Pet Supplies"
                        },
                        new
                        {
                            Id = new Guid("ee522e93-b3fb-42e2-95db-a7416cf471f9"),
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = new Guid("449f55bb-2187-4c6d-8729-0cad57f4e3ce"),
                            Name = "Grocery & Gourmet Foods"
                        },
                        new
                        {
                            Id = new Guid("f8120132-9014-4007-94ae-94f051d133a3"),
                            Name = "Baby Products"
                        },
                        new
                        {
                            Id = new Guid("333d7bc4-17d0-4a14-a0ed-33b3b7fcd0c7"),
                            Name = "Music & Instruments"
                        },
                        new
                        {
                            Id = new Guid("7adbe25d-8b15-47c2-802a-c610d37be591"),
                            Name = "Watches"
                        },
                        new
                        {
                            Id = new Guid("ed726b35-c6d5-4061-ad4f-fa8721d45569"),
                            Name = "Handmade & Artisanal"
                        },
                        new
                        {
                            Id = new Guid("a5bc1cc4-4fb9-4f60-ae3e-7bfe04dcf344"),
                            Name = "Industrial & Scientific"
                        });
                });

            modelBuilder.Entity("MeeshoWebClone.Models.ProductColor", b =>
                {
                    b.Property<Guid>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColorId");

                    b.ToTable("ProductColors");

                    b.HasData(
                        new
                        {
                            ColorId = new Guid("74d94ba3-0bad-423a-af18-95438a02ec06"),
                            ColorHex = "#FF0000",
                            ColorName = "Red"
                        },
                        new
                        {
                            ColorId = new Guid("2bdadefd-3441-4142-b413-79342f90d0e4"),
                            ColorHex = "#0000FF",
                            ColorName = "Blue"
                        },
                        new
                        {
                            ColorId = new Guid("23cf48ef-fda1-4eb8-bf88-5afd6c8b45eb"),
                            ColorHex = "#008000",
                            ColorName = "Green"
                        },
                        new
                        {
                            ColorId = new Guid("7ccc35fe-bf44-42c4-964e-97f212698785"),
                            ColorHex = "#FFFF00",
                            ColorName = "Yellow"
                        },
                        new
                        {
                            ColorId = new Guid("1ee45a0b-0ae2-49f3-a4dd-9bbd3dea912b"),
                            ColorHex = "#000000",
                            ColorName = "Black"
                        },
                        new
                        {
                            ColorId = new Guid("3b9e89bb-a565-496d-b60e-93c83b56627a"),
                            ColorHex = "#FFFFFF",
                            ColorName = "White"
                        },
                        new
                        {
                            ColorId = new Guid("b0a18e64-5517-48fb-bec1-b874c4199a84"),
                            ColorHex = "#808080",
                            ColorName = "Gray"
                        },
                        new
                        {
                            ColorId = new Guid("1a6d88ca-1faa-425c-8792-aeb8b71f9419"),
                            ColorHex = "#800080",
                            ColorName = "Purple"
                        },
                        new
                        {
                            ColorId = new Guid("1714d8c2-d378-4044-bb3a-c24c59a9668e"),
                            ColorHex = "#FFC0CB",
                            ColorName = "Pink"
                        },
                        new
                        {
                            ColorId = new Guid("870a506c-d964-4b41-bbb6-6c047e9a027d"),
                            ColorHex = "#FFA500",
                            ColorName = "Orange"
                        },
                        new
                        {
                            ColorId = new Guid("c00c8c70-7fe1-4c7f-87d2-21767302735e"),
                            ColorHex = "#A52A2A",
                            ColorName = "Brown"
                        });
                });

            modelBuilder.Entity("MeeshoWebClone.Models.ProductColorMapping", b =>
                {
                    b.Property<Guid>("ProductColorMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductColorMappingId");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductColorMappings");
                });

            modelBuilder.Entity("MeeshoWebClone.Models.ProductImage", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("MeeshoWebClone.Models.ProductSize", b =>
                {
                    b.Property<Guid>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SizeId");

                    b.ToTable("ProductSizes");

                    b.HasData(
                        new
                        {
                            SizeId = new Guid("e9eb11e3-f518-4edf-b46a-73dfbfe7e336"),
                            Size = "XS"
                        },
                        new
                        {
                            SizeId = new Guid("5ab8f500-ec5f-4464-bf47-4ec3a998dca1"),
                            Size = "S"
                        },
                        new
                        {
                            SizeId = new Guid("786842d7-b2df-4331-9237-3930e1b7b3c0"),
                            Size = "M"
                        },
                        new
                        {
                            SizeId = new Guid("0315c799-f095-4125-94c8-26859d9363f2"),
                            Size = "L"
                        },
                        new
                        {
                            SizeId = new Guid("e71444c0-5e9d-4eec-8812-5ebbdfaaa2a4"),
                            Size = "XL"
                        },
                        new
                        {
                            SizeId = new Guid("46469af4-bbea-4d0f-99f4-42581a2eb1e2"),
                            Size = "XXL"
                        },
                        new
                        {
                            SizeId = new Guid("f819771f-00c0-4f8f-b352-bf7d213d9f24"),
                            Size = "3XL"
                        },
                        new
                        {
                            SizeId = new Guid("53d45c1b-11b8-47a4-9571-250144ccc256"),
                            Size = "4XL"
                        },
                        new
                        {
                            SizeId = new Guid("c6f1b298-842a-425a-bffa-03fe522f4e6c"),
                            Size = "5XL"
                        },
                        new
                        {
                            SizeId = new Guid("69e006bd-e9aa-476b-8761-557e9fc5fca1"),
                            Size = "6XL"
                        },
                        new
                        {
                            SizeId = new Guid("a947fc26-5c47-4b18-af19-9144a657edd7"),
                            Size = "Free Size"
                        });
                });

            modelBuilder.Entity("MeeshoWebClone.Models.ProductSizeMapping", b =>
                {
                    b.Property<Guid>("ProductSizeMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SizeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductSizeMappingId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SizeId");

                    b.ToTable("ProductSizeMappings");
                });

            modelBuilder.Entity("MeeshoWebClone.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MeeshoWebClone.Models.UserLikedProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLikedProducts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MeeshoWebClone.Models.CartItem", b =>
                {
                    b.HasOne("MeeshoWebClone.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeeshoWebClone.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeeshoWebClone.Models.Product", b =>
                {
                    b.HasOne("MeeshoWebClone.Models.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeeshoWebClone.Models.User", "Seller")
                        .WithMany("Products")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("MeeshoWebClone.Models.ProductColorMapping", b =>
                {
                    b.HasOne("MeeshoWebClone.Models.ProductColor", null)
                        .WithMany("ProductColorMappings")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeeshoWebClone.Models.Product", null)
                        .WithMany("ProductColorMappings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeeshoWebClone.Models.ProductImage", b =>
                {
                    b.HasOne("MeeshoWebClone.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MeeshoWebClone.Models.ProductSizeMapping", b =>
                {
                    b.HasOne("MeeshoWebClone.Models.Product", null)
                        .WithMany("ProductSizeMappings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeeshoWebClone.Models.ProductSize", null)
                        .WithMany("ProductSizeMappings")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeeshoWebClone.Models.UserLikedProduct", b =>
                {
                    b.HasOne("MeeshoWebClone.Models.Product", "Product")
                        .WithMany("LikedByUsers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeeshoWebClone.Models.User", "User")
                        .WithMany("LikedProducts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MeeshoWebClone.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MeeshoWebClone.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeeshoWebClone.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MeeshoWebClone.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeeshoWebClone.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Images");

                    b.Navigation("LikedByUsers");

                    b.Navigation("ProductColorMappings");

                    b.Navigation("ProductSizeMappings");
                });

            modelBuilder.Entity("MeeshoWebClone.Models.ProductColor", b =>
                {
                    b.Navigation("ProductColorMappings");
                });

            modelBuilder.Entity("MeeshoWebClone.Models.ProductSize", b =>
                {
                    b.Navigation("ProductSizeMappings");
                });

            modelBuilder.Entity("MeeshoWebClone.Models.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("LikedProducts");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
